language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ayushj98/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ayushj98/docker-react npm run test
